# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: compython pack

on:
  release:
    types: [published]


jobs:
  build-n-publish:
    name: compython pack
    runs-on: ubuntu-latest
    
    
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9


    - name: Install dependencies/build
      run: |
          python -m pip install --upgrade pip 
          python3 -m pip install twine
          python -m pip install build 
    - name: Build a binary wheel and a source tarball
      run: |
        python -m build --sdist
        python -m build --sdist
        python -m build --wheel

    - name: compython to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        
